//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SAN.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SANParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
public interface ISANVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.san_game"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSan_game([NotNull] SANParser.San_gameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.san_termination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSan_termination([NotNull] SANParser.San_terminationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.san_sequence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSan_sequence([NotNull] SANParser.San_sequenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.san_move"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSan_move([NotNull] SANParser.San_moveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.piece_moves"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPiece_moves([NotNull] SANParser.Piece_movesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.piece_moves_A1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPiece_moves_A1([NotNull] SANParser.Piece_moves_A1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.piece_moves_A2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPiece_moves_A2([NotNull] SANParser.Piece_moves_A2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.piece_moves_A3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPiece_moves_A3([NotNull] SANParser.Piece_moves_A3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.piece_move_capture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPiece_move_capture([NotNull] SANParser.Piece_move_captureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.piece_move_capture_A1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPiece_move_capture_A1([NotNull] SANParser.Piece_move_capture_A1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.piece_move_capture_A2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPiece_move_capture_A2([NotNull] SANParser.Piece_move_capture_A2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.piece_move_capture_A3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPiece_move_capture_A3([NotNull] SANParser.Piece_move_capture_A3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.pawn_push"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPawn_push([NotNull] SANParser.Pawn_pushContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.pawn_push_promote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPawn_push_promote([NotNull] SANParser.Pawn_push_promoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.pawn_capture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPawn_capture([NotNull] SANParser.Pawn_captureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.pawn_capture_A1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPawn_capture_A1([NotNull] SANParser.Pawn_capture_A1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.pawn_capture_promote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPawn_capture_promote([NotNull] SANParser.Pawn_capture_promoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.pawn_capture_promote_A1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPawn_capture_promote_A1([NotNull] SANParser.Pawn_capture_promote_A1Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.castle_king"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastle_king([NotNull] SANParser.Castle_kingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SANParser.castle_queen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastle_queen([NotNull] SANParser.Castle_queenContext context);
}
